### ISSUE TITLE
cant save settings

### ISSUE THREAD

**Issue by sip-lean** [Dev0Louis/Unbound-FoV#1]
After installing the mod, closing the game, and reopening resets all saved settings, such as video, controls, etc

**Comment by idkwidsb** [comment]
me too

**Comment by Dev0Louis** [comment]
Oh I will look into that, thanks for reporting that.

**Comment by Dev0Louis** [comment]
Fixed with https://github.com/Dev0Louis/Unbound-FoV/commit/2e6074504d116a570f8d47e72478853566c6badc.
The fix is available as of 1.0.2 on Modrinth:
https://modrinth.com/mod/unbound-fov/version/1.0.2

**Comment by Legacy7K** [comment]
> Fixed with [2e60745](https://github.com/Dev0Louis/Unbound-FoV/commit/2e6074504d116a570f8d47e72478853566c6badc). The fix is available as of 1.0.2 on Modrinth: https://modrinth.com/mod/unbound-fov/version/1.0.2

This fix is does not seem to work as of 1.0.2 on Modrinth. Updated version. Still resets after game restart.
