### ISSUE TITLE
FlexFOV

### ISSUE THREAD

**Issue by deadhitter1** [Dev0Louis/Unbound-FoV#3]
Can you make it so that 360FOV actually does something useful like in FlexFOV
Asking because FlexFOV stopped updating and there is no fabric 1.20.1 version
I need my mercator projection minecraft
https://www.youtube.com/watch?v=6B7BodzjMgA

**Comment by Dev0Louis** [comment]
I do not plan on doing this in this mod. And don't have the time to start a new project for something like that.
